### ISSUE TITLE
Trouble getting weather or could not detect internet

### ISSUE THREAD

**Issue by jepp4561** [Cyndakwil/Wallpaper-Wizard#11]
So far I have not been able to run the actual program, because every time I run it, it gives me the error message that it couldn't detect the weather, or that it couldn't  detect an internet connection. I have an internet connection and I haven't had a chance to put in a location anywhere, since it crashes when I try to run it.

**Comment by phlppwrnck** [comment]
Same for me. Have tried a lot, like switching firewall and antivirus off and on but nothing changed that problem.

**Comment by rohan-shettyy** [comment]
Currently working on a fix. Basically there are too many users and the traffic has caused the API key to be disabled. I will likely just have you input your own api key to simplify things.

**Comment by rohan-shettyy** [comment]
Finally fixed. Sorry about the delay. Please check itch.io for the release.
