### ISSUE TITLE
Location Error

### ISSUE THREAD

**Issue by apreo** [Cyndakwil/Wallpaper-Wizard#12]
I get this error when opening Wallpaper Wizard: 
![image](https://user-images.githubusercontent.com/77218041/104112940-6da19e80-52ec-11eb-8664-71dddef42404.png)

I have tried disabling firewall/antivirus and that has not resolved the issue.
Thanks in advance.

**Comment by chanicorn** [comment]
I have the same issue! I miss my changing wallpapers so much, hopefully this gets fixed.

**Comment by Krushaaaa** [comment]
Is there a fix for this yet?

**Comment by Enzo12z** [comment]
same here, any fix yet?

**Comment by rohan-shettyy** [comment]
Finally fixed. Sorry about the delay. Please check itch.io for the release.
