### ISSUE TITLE
Low resolution wallpapers on 1080p screen

### ISSUE THREAD

**Issue by shivv3r** [Cyndakwil/Wallpaper-Wizard#3]
As briefly explained on reddit - I'm having issue with low resolution wallpapers. My monitor is FULL HD, but sometimes the wallpapers look like if they were only HD or even lower. No idea why this is happening. Attaching screenshot. 
![snip1](https://user-images.githubusercontent.com/63784451/80648182-039fdc80-8a70-11ea-898c-3015542aa809.png)

**Comment by rohan-shettyy** [comment]
Oops, I can't believe I missed that! The Firewatch rain wallpaper was an extremely low resolution. I updated the app on itch.io with a 1440p rain wallpaper and a sunset, snow, and thunderstorm variant for Firewatch. Enjoy!

**Comment by shivv3r** [comment]
Thanks ;) It's good now. Except the other bug that I've reported that I'm not able to change the themes.
