### ISSUE TITLE
App crashes after trying to import a theme

### ISSUE THREAD

**Issue by diemer** [Cyndakwil/Wallpaper-Wizard#5]
I made a theme and tried to import it, and since then it crashes with this error in the Event Viewer:

```
Exception Info: System.ArgumentException
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at Wallpaper_Wizard.MainWindow.RefreshThemes()
   at Wallpaper_Wizard.MainWindow..ctor()
```

**Comment by rohan-shettyy** [comment]
Can you check if all the values in your `theme.json` file are spelled correctly?

**Comment by rohan-shettyy** [comment]
@diemer can you also make sure you are sending the files into a zip, not the parent folder?

**Comment by diemer** [comment]
All the values are correct. I only have two wallpaper I want to use, Day and Night, so I've just stubbed out the rest. It looks like this:
```
{
    "Title": "Street by Arsenixc",
    "Day": "Street_day.jpg",
    "Night": "Street_night.jpg",
    "Sunset": "Street_day.jpg",
    "Rain": "Street_day.jpg",
    "Thunderstorm": "Street_day.jpg",
    "Clouds": "Street_day.jpg",
    "Snow": "Street_day.jpg",
    "Fog": "Street_day.jpg"
}
```

Important to note that the app no longer works at all. It crashes if I mouse over the icon in the systray. It's like it has corrupt data and I don't know how to clear it. I've uninstalled and reinstalled it but it does the same thing.

**Comment by diemer** [comment]
Was able to get the app built using Visual Studio and it looks like the issue is with the spaces in the Title field. It gets used as the Name of a Button on` line 243` of `MainWindow.xaml.cs`, and it seems like spaces there are invalid.

**Comment by rohan-shettyy** [comment]
Wonderful, thanks for your help! I'll write a quick fix and re-upload it.
