### ISSUE TITLE
Can't Add Custom Theme

### ISSUE THREAD

**Issue by GiaRed** [Cyndakwil/Wallpaper-Wizard#7]
I followed the steps in the guide but am unable to add it and get given an error.
Below are a screencap of the error message and my theme.

[2020-06-28_15-10-43](https://user-images.githubusercontent.com/67559058/85957692-8a344580-b95d-11ea-87e3-5ee345175b70.png)
[Violet Evergarden Theme.zip](https://github.com/Cyndakwil/Wallpaper-Wizard/files/4842966/Violet.Evergarden.Theme.zip)

**Comment by rohan-shettyy** [comment]
Looks like on line 9 of `theme.json` where you outlined the Snow file, you forgot a comma at the end of the line. I'll look into making the error message more clear when something like that happens.
