### ISSUE TITLE
downloading as a document?

### ISSUE THREAD

**Issue by hanamix** [Cyndakwil/Wallpaper-Wizard#9]
The wizard downloads as a document and then asks for me to open the file through another app and I'm not sure what I'm doing wrong

**Comment by rohan-shettyy** [comment]
@hanamix sorry for the late reply. Can you please describe how you are downloading the installer?

**Comment by hanamix** [comment]
I'm just clicking the red download button on the itch.io page, I say continue to download, and it automatically downloads as a .msi, and my computer says I need some kind of application to open it. I tried extracting the files from it, but I still couldn't find an install wizard.
    On Wednesday, July 15, 2020, 09:10:33 PM CDT, Rohan Shetty <notifications@github.com> wrote:  
 
 


@hanamix can you please describe how you are downloading the installer?

**Comment by rohan-shettyy** [comment]
@hanamix Interesting. MSI is a very well-known installer type for Windows and you should only have to double-click the file to install. Are you perhaps on MacOS or Linux?

**Comment by hanamix** [comment]
Oh yes, I just started using MacOS. I was unaware that MSI wouldn't work the same on my new computer. Is there any way for me to modify it so that it works on MacOS? 
    On Friday, July 17, 2020, 01:16:30 PM CDT, Rohan Shetty <notifications@github.com> wrote:  
 
 


Interesting. MSI is a very well-known installer type for Windows and you should only have to double-click the file to install. Are you perhaps on MacOS or Linux?

**Comment by rohan-shettyy** [comment]
Unfortunately no, there are differences in the way Windows and MacOS allow the wallpaper to be changed, not to mention the entire framework the app is based on is Windows only. If there is enough support, I would love to develop a version for MacOS but it will take me a little while as I have absolutely no experience with Macs.

**Comment by hanamix** [comment]
Got it, I would love to see it! I'm sorry to have wasted your time, and let me know if there's any way I can support, good luck!
    On Friday, July 17, 2020, 01:42:44 PM CDT, Rohan Shetty <notifications@github.com> wrote:  
 
 


Unfortunately no, there are differences in the way Windows and MacOS allow the wallpaper to be changed. If there is enough support, I would love to develop a version for MacOS but it will take me a little while as I have absolutely no experience with Macs.
